// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: move.proto

package com.example.wewrite;

public final class MovesProtos {
  private MovesProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MoveOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string baseText = 1;
    /**
     * <code>optional string baseText = 1;</code>
     *
     * <pre>
     *if this is filled out, then we know it is the base file
     * </pre>
     */
    boolean hasBaseText();
    /**
     * <code>optional string baseText = 1;</code>
     *
     * <pre>
     *if this is filled out, then we know it is the base file
     * </pre>
     */
    java.lang.String getBaseText();
    /**
     * <code>optional string baseText = 1;</code>
     *
     * <pre>
     *if this is filled out, then we know it is the base file
     * </pre>
     */
    com.google.protobuf.ByteString
        getBaseTextBytes();

    // optional int32 userId = 2;
    /**
     * <code>optional int32 userId = 2;</code>
     *
     * <pre>
     *who sent the message
     * </pre>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 userId = 2;</code>
     *
     * <pre>
     *who sent the message
     * </pre>
     */
    int getUserId();

    // optional int32 moveId = 3;
    /**
     * <code>optional int32 moveId = 3;</code>
     *
     * <pre>
     *just a random number string to identify repeated moves
     * </pre>
     */
    boolean hasMoveId();
    /**
     * <code>optional int32 moveId = 3;</code>
     *
     * <pre>
     *just a random number string to identify repeated moves
     * </pre>
     */
    int getMoveId();

    // optional int32 orderId = 4;
    /**
     * <code>optional int32 orderId = 4;</code>
     */
    boolean hasOrderId();
    /**
     * <code>optional int32 orderId = 4;</code>
     */
    int getOrderId();

    // optional int32 moveType = 5;
    /**
     * <code>optional int32 moveType = 5;</code>
     *
     * <pre>
     *ADD, DELETE, CURSOR, INIT
     * </pre>
     */
    boolean hasMoveType();
    /**
     * <code>optional int32 moveType = 5;</code>
     *
     * <pre>
     *ADD, DELETE, CURSOR, INIT
     * </pre>
     */
    int getMoveType();

    // optional string data = 6;
    /**
     * <code>optional string data = 6;</code>
     *
     * <pre>
     *what is to be added on an "ADD"
     * </pre>
     */
    boolean hasData();
    /**
     * <code>optional string data = 6;</code>
     *
     * <pre>
     *what is to be added on an "ADD"
     * </pre>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 6;</code>
     *
     * <pre>
     *what is to be added on an "ADD"
     * </pre>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    // optional int32 cursorChange = 7;
    /**
     * <code>optional int32 cursorChange = 7;</code>
     *
     * <pre>
     *where, relatively, the cursor is moving to
     * </pre>
     */
    boolean hasCursorChange();
    /**
     * <code>optional int32 cursorChange = 7;</code>
     *
     * <pre>
     *where, relatively, the cursor is moving to
     * </pre>
     */
    int getCursorChange();

    // optional int32 undo = 8;
    /**
     * <code>optional int32 undo = 8;</code>
     *
     * <pre>
     *0, 1 = unodo, 2 = redo
     * </pre>
     */
    boolean hasUndo();
    /**
     * <code>optional int32 undo = 8;</code>
     *
     * <pre>
     *0, 1 = unodo, 2 = redo
     * </pre>
     */
    int getUndo();
  }
  /**
   * Protobuf type {@code TextEditor1.Move}
   */
  public static final class Move extends
      com.google.protobuf.GeneratedMessage
      implements MoveOrBuilder {
    // Use Move.newBuilder() to construct.
    private Move(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Move(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Move defaultInstance;
    public static Move getDefaultInstance() {
      return defaultInstance;
    }

    public Move getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Move(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              baseText_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              moveId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              orderId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              moveType_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              data_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              cursorChange_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              undo_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.wewrite.MovesProtos.internal_static_TextEditor1_Move_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.wewrite.MovesProtos.internal_static_TextEditor1_Move_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.wewrite.MovesProtos.Move.class, com.example.wewrite.MovesProtos.Move.Builder.class);
    }

    public static com.google.protobuf.Parser<Move> PARSER =
        new com.google.protobuf.AbstractParser<Move>() {
      public Move parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Move(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Move> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string baseText = 1;
    public static final int BASETEXT_FIELD_NUMBER = 1;
    private java.lang.Object baseText_;
    /**
     * <code>optional string baseText = 1;</code>
     *
     * <pre>
     *if this is filled out, then we know it is the base file
     * </pre>
     */
    public boolean hasBaseText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string baseText = 1;</code>
     *
     * <pre>
     *if this is filled out, then we know it is the base file
     * </pre>
     */
    public java.lang.String getBaseText() {
      java.lang.Object ref = baseText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          baseText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string baseText = 1;</code>
     *
     * <pre>
     *if this is filled out, then we know it is the base file
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBaseTextBytes() {
      java.lang.Object ref = baseText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>optional int32 userId = 2;</code>
     *
     * <pre>
     *who sent the message
     * </pre>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 userId = 2;</code>
     *
     * <pre>
     *who sent the message
     * </pre>
     */
    public int getUserId() {
      return userId_;
    }

    // optional int32 moveId = 3;
    public static final int MOVEID_FIELD_NUMBER = 3;
    private int moveId_;
    /**
     * <code>optional int32 moveId = 3;</code>
     *
     * <pre>
     *just a random number string to identify repeated moves
     * </pre>
     */
    public boolean hasMoveId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 moveId = 3;</code>
     *
     * <pre>
     *just a random number string to identify repeated moves
     * </pre>
     */
    public int getMoveId() {
      return moveId_;
    }

    // optional int32 orderId = 4;
    public static final int ORDERID_FIELD_NUMBER = 4;
    private int orderId_;
    /**
     * <code>optional int32 orderId = 4;</code>
     */
    public boolean hasOrderId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 orderId = 4;</code>
     */
    public int getOrderId() {
      return orderId_;
    }

    // optional int32 moveType = 5;
    public static final int MOVETYPE_FIELD_NUMBER = 5;
    private int moveType_;
    /**
     * <code>optional int32 moveType = 5;</code>
     *
     * <pre>
     *ADD, DELETE, CURSOR, INIT
     * </pre>
     */
    public boolean hasMoveType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 moveType = 5;</code>
     *
     * <pre>
     *ADD, DELETE, CURSOR, INIT
     * </pre>
     */
    public int getMoveType() {
      return moveType_;
    }

    // optional string data = 6;
    public static final int DATA_FIELD_NUMBER = 6;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 6;</code>
     *
     * <pre>
     *what is to be added on an "ADD"
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string data = 6;</code>
     *
     * <pre>
     *what is to be added on an "ADD"
     * </pre>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 6;</code>
     *
     * <pre>
     *what is to be added on an "ADD"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 cursorChange = 7;
    public static final int CURSORCHANGE_FIELD_NUMBER = 7;
    private int cursorChange_;
    /**
     * <code>optional int32 cursorChange = 7;</code>
     *
     * <pre>
     *where, relatively, the cursor is moving to
     * </pre>
     */
    public boolean hasCursorChange() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 cursorChange = 7;</code>
     *
     * <pre>
     *where, relatively, the cursor is moving to
     * </pre>
     */
    public int getCursorChange() {
      return cursorChange_;
    }

    // optional int32 undo = 8;
    public static final int UNDO_FIELD_NUMBER = 8;
    private int undo_;
    /**
     * <code>optional int32 undo = 8;</code>
     *
     * <pre>
     *0, 1 = unodo, 2 = redo
     * </pre>
     */
    public boolean hasUndo() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 undo = 8;</code>
     *
     * <pre>
     *0, 1 = unodo, 2 = redo
     * </pre>
     */
    public int getUndo() {
      return undo_;
    }

    private void initFields() {
      baseText_ = "";
      userId_ = 0;
      moveId_ = 0;
      orderId_ = 0;
      moveType_ = 0;
      data_ = "";
      cursorChange_ = 0;
      undo_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBaseTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, moveId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, orderId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, moveType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDataBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, cursorChange_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, undo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBaseTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, moveId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, orderId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, moveType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDataBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, cursorChange_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, undo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.wewrite.MovesProtos.Move parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.wewrite.MovesProtos.Move parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.wewrite.MovesProtos.Move parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.wewrite.MovesProtos.Move parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.wewrite.MovesProtos.Move parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.wewrite.MovesProtos.Move parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.wewrite.MovesProtos.Move parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.wewrite.MovesProtos.Move parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.wewrite.MovesProtos.Move parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.wewrite.MovesProtos.Move parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.wewrite.MovesProtos.Move prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TextEditor1.Move}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.wewrite.MovesProtos.MoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.wewrite.MovesProtos.internal_static_TextEditor1_Move_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.wewrite.MovesProtos.internal_static_TextEditor1_Move_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.wewrite.MovesProtos.Move.class, com.example.wewrite.MovesProtos.Move.Builder.class);
      }

      // Construct using com.example.wewrite.MovesProtos.Move.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        baseText_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        moveId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        orderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        moveType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        cursorChange_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        undo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.wewrite.MovesProtos.internal_static_TextEditor1_Move_descriptor;
      }

      public com.example.wewrite.MovesProtos.Move getDefaultInstanceForType() {
        return com.example.wewrite.MovesProtos.Move.getDefaultInstance();
      }

      public com.example.wewrite.MovesProtos.Move build() {
        com.example.wewrite.MovesProtos.Move result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.wewrite.MovesProtos.Move buildPartial() {
        com.example.wewrite.MovesProtos.Move result = new com.example.wewrite.MovesProtos.Move(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.baseText_ = baseText_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.moveId_ = moveId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.orderId_ = orderId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.moveType_ = moveType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.cursorChange_ = cursorChange_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.undo_ = undo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.wewrite.MovesProtos.Move) {
          return mergeFrom((com.example.wewrite.MovesProtos.Move)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.wewrite.MovesProtos.Move other) {
        if (other == com.example.wewrite.MovesProtos.Move.getDefaultInstance()) return this;
        if (other.hasBaseText()) {
          bitField0_ |= 0x00000001;
          baseText_ = other.baseText_;
          onChanged();
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasMoveId()) {
          setMoveId(other.getMoveId());
        }
        if (other.hasOrderId()) {
          setOrderId(other.getOrderId());
        }
        if (other.hasMoveType()) {
          setMoveType(other.getMoveType());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000020;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasCursorChange()) {
          setCursorChange(other.getCursorChange());
        }
        if (other.hasUndo()) {
          setUndo(other.getUndo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.wewrite.MovesProtos.Move parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.wewrite.MovesProtos.Move) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string baseText = 1;
      private java.lang.Object baseText_ = "";
      /**
       * <code>optional string baseText = 1;</code>
       *
       * <pre>
       *if this is filled out, then we know it is the base file
       * </pre>
       */
      public boolean hasBaseText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string baseText = 1;</code>
       *
       * <pre>
       *if this is filled out, then we know it is the base file
       * </pre>
       */
      public java.lang.String getBaseText() {
        java.lang.Object ref = baseText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          baseText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string baseText = 1;</code>
       *
       * <pre>
       *if this is filled out, then we know it is the base file
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBaseTextBytes() {
        java.lang.Object ref = baseText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string baseText = 1;</code>
       *
       * <pre>
       *if this is filled out, then we know it is the base file
       * </pre>
       */
      public Builder setBaseText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        baseText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string baseText = 1;</code>
       *
       * <pre>
       *if this is filled out, then we know it is the base file
       * </pre>
       */
      public Builder clearBaseText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        baseText_ = getDefaultInstance().getBaseText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string baseText = 1;</code>
       *
       * <pre>
       *if this is filled out, then we know it is the base file
       * </pre>
       */
      public Builder setBaseTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        baseText_ = value;
        onChanged();
        return this;
      }

      // optional int32 userId = 2;
      private int userId_ ;
      /**
       * <code>optional int32 userId = 2;</code>
       *
       * <pre>
       *who sent the message
       * </pre>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 userId = 2;</code>
       *
       * <pre>
       *who sent the message
       * </pre>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 2;</code>
       *
       * <pre>
       *who sent the message
       * </pre>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 2;</code>
       *
       * <pre>
       *who sent the message
       * </pre>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 moveId = 3;
      private int moveId_ ;
      /**
       * <code>optional int32 moveId = 3;</code>
       *
       * <pre>
       *just a random number string to identify repeated moves
       * </pre>
       */
      public boolean hasMoveId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 moveId = 3;</code>
       *
       * <pre>
       *just a random number string to identify repeated moves
       * </pre>
       */
      public int getMoveId() {
        return moveId_;
      }
      /**
       * <code>optional int32 moveId = 3;</code>
       *
       * <pre>
       *just a random number string to identify repeated moves
       * </pre>
       */
      public Builder setMoveId(int value) {
        bitField0_ |= 0x00000004;
        moveId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 moveId = 3;</code>
       *
       * <pre>
       *just a random number string to identify repeated moves
       * </pre>
       */
      public Builder clearMoveId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        moveId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 orderId = 4;
      private int orderId_ ;
      /**
       * <code>optional int32 orderId = 4;</code>
       */
      public boolean hasOrderId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 orderId = 4;</code>
       */
      public int getOrderId() {
        return orderId_;
      }
      /**
       * <code>optional int32 orderId = 4;</code>
       */
      public Builder setOrderId(int value) {
        bitField0_ |= 0x00000008;
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 orderId = 4;</code>
       */
      public Builder clearOrderId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        orderId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 moveType = 5;
      private int moveType_ ;
      /**
       * <code>optional int32 moveType = 5;</code>
       *
       * <pre>
       *ADD, DELETE, CURSOR, INIT
       * </pre>
       */
      public boolean hasMoveType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 moveType = 5;</code>
       *
       * <pre>
       *ADD, DELETE, CURSOR, INIT
       * </pre>
       */
      public int getMoveType() {
        return moveType_;
      }
      /**
       * <code>optional int32 moveType = 5;</code>
       *
       * <pre>
       *ADD, DELETE, CURSOR, INIT
       * </pre>
       */
      public Builder setMoveType(int value) {
        bitField0_ |= 0x00000010;
        moveType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 moveType = 5;</code>
       *
       * <pre>
       *ADD, DELETE, CURSOR, INIT
       * </pre>
       */
      public Builder clearMoveType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        moveType_ = 0;
        onChanged();
        return this;
      }

      // optional string data = 6;
      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 6;</code>
       *
       * <pre>
       *what is to be added on an "ADD"
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string data = 6;</code>
       *
       * <pre>
       *what is to be added on an "ADD"
       * </pre>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 6;</code>
       *
       * <pre>
       *what is to be added on an "ADD"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 6;</code>
       *
       * <pre>
       *what is to be added on an "ADD"
       * </pre>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 6;</code>
       *
       * <pre>
       *what is to be added on an "ADD"
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 6;</code>
       *
       * <pre>
       *what is to be added on an "ADD"
       * </pre>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }

      // optional int32 cursorChange = 7;
      private int cursorChange_ ;
      /**
       * <code>optional int32 cursorChange = 7;</code>
       *
       * <pre>
       *where, relatively, the cursor is moving to
       * </pre>
       */
      public boolean hasCursorChange() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 cursorChange = 7;</code>
       *
       * <pre>
       *where, relatively, the cursor is moving to
       * </pre>
       */
      public int getCursorChange() {
        return cursorChange_;
      }
      /**
       * <code>optional int32 cursorChange = 7;</code>
       *
       * <pre>
       *where, relatively, the cursor is moving to
       * </pre>
       */
      public Builder setCursorChange(int value) {
        bitField0_ |= 0x00000040;
        cursorChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorChange = 7;</code>
       *
       * <pre>
       *where, relatively, the cursor is moving to
       * </pre>
       */
      public Builder clearCursorChange() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cursorChange_ = 0;
        onChanged();
        return this;
      }

      // optional int32 undo = 8;
      private int undo_ ;
      /**
       * <code>optional int32 undo = 8;</code>
       *
       * <pre>
       *0, 1 = unodo, 2 = redo
       * </pre>
       */
      public boolean hasUndo() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 undo = 8;</code>
       *
       * <pre>
       *0, 1 = unodo, 2 = redo
       * </pre>
       */
      public int getUndo() {
        return undo_;
      }
      /**
       * <code>optional int32 undo = 8;</code>
       *
       * <pre>
       *0, 1 = unodo, 2 = redo
       * </pre>
       */
      public Builder setUndo(int value) {
        bitField0_ |= 0x00000080;
        undo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 undo = 8;</code>
       *
       * <pre>
       *0, 1 = unodo, 2 = redo
       * </pre>
       */
      public Builder clearUndo() {
        bitField0_ = (bitField0_ & ~0x00000080);
        undo_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TextEditor1.Move)
    }

    static {
      defaultInstance = new Move(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TextEditor1.Move)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TextEditor1_Move_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TextEditor1_Move_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmove.proto\022\013TextEditor1\"\215\001\n\004Move\022\020\n\010ba" +
      "seText\030\001 \001(\t\022\016\n\006userId\030\002 \001(\005\022\016\n\006moveId\030\003" +
      " \001(\005\022\017\n\007orderId\030\004 \001(\005\022\020\n\010moveType\030\005 \001(\005\022" +
      "\014\n\004data\030\006 \001(\t\022\024\n\014cursorChange\030\007 \001(\005\022\014\n\004u" +
      "ndo\030\010 \001(\005B\037\n\020com.example.wewriteB\013MovesProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TextEditor1_Move_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TextEditor1_Move_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TextEditor1_Move_descriptor,
              new java.lang.String[] { "BaseText", "UserId", "MoveId", "OrderId", "MoveType", "Data", "CursorChange", "Undo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
