// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moves.proto

package com.example.wewrite;

public final class MoveProtoData {
  private MoveProtoData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface protoDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 user_id = 1;
    /**
     * <code>optional int64 user_id = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int64 user_id = 1;</code>
     */
    long getUserId();

    // optional int32 move_type = 2;
    /**
     * <code>optional int32 move_type = 2;</code>
     */
    boolean hasMoveType();
    /**
     * <code>optional int32 move_type = 2;</code>
     */
    int getMoveType();

    // optional string text = 3;
    /**
     * <code>optional string text = 3;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 3;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 3;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    // optional int64 cursor_change = 4;
    /**
     * <code>optional int64 cursor_change = 4;</code>
     */
    boolean hasCursorChange();
    /**
     * <code>optional int64 cursor_change = 4;</code>
     */
    long getCursorChange();

    // optional bool valid = 5;
    /**
     * <code>optional bool valid = 5;</code>
     */
    boolean hasValid();
    /**
     * <code>optional bool valid = 5;</code>
     */
    boolean getValid();
  }
  /**
   * Protobuf type {@code wewrite.protoData}
   */
  public static final class protoData extends
      com.google.protobuf.GeneratedMessage
      implements protoDataOrBuilder {
    // Use protoData.newBuilder() to construct.
    private protoData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private protoData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final protoData defaultInstance;
    public static protoData getDefaultInstance() {
      return defaultInstance;
    }

    public protoData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private protoData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              moveType_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              text_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              cursorChange_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              valid_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.wewrite.MoveProtoData.internal_static_wewrite_protoData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.wewrite.MoveProtoData.internal_static_wewrite_protoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.wewrite.MoveProtoData.protoData.class, com.example.wewrite.MoveProtoData.protoData.Builder.class);
    }

    public static com.google.protobuf.Parser<protoData> PARSER =
        new com.google.protobuf.AbstractParser<protoData>() {
      public protoData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new protoData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<protoData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>optional int64 user_id = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // optional int32 move_type = 2;
    public static final int MOVE_TYPE_FIELD_NUMBER = 2;
    private int moveType_;
    /**
     * <code>optional int32 move_type = 2;</code>
     */
    public boolean hasMoveType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 move_type = 2;</code>
     */
    public int getMoveType() {
      return moveType_;
    }

    // optional string text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 3;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string text = 3;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 cursor_change = 4;
    public static final int CURSOR_CHANGE_FIELD_NUMBER = 4;
    private long cursorChange_;
    /**
     * <code>optional int64 cursor_change = 4;</code>
     */
    public boolean hasCursorChange() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 cursor_change = 4;</code>
     */
    public long getCursorChange() {
      return cursorChange_;
    }

    // optional bool valid = 5;
    public static final int VALID_FIELD_NUMBER = 5;
    private boolean valid_;
    /**
     * <code>optional bool valid = 5;</code>
     */
    public boolean hasValid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool valid = 5;</code>
     */
    public boolean getValid() {
      return valid_;
    }

    private void initFields() {
      userId_ = 0L;
      moveType_ = 0;
      text_ = "";
      cursorChange_ = 0L;
      valid_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, moveType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, cursorChange_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, valid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, moveType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, cursorChange_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, valid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.wewrite.MoveProtoData.protoData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.wewrite.MoveProtoData.protoData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.wewrite.MoveProtoData.protoData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wewrite.protoData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.wewrite.MoveProtoData.protoDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.wewrite.MoveProtoData.internal_static_wewrite_protoData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.wewrite.MoveProtoData.internal_static_wewrite_protoData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.wewrite.MoveProtoData.protoData.class, com.example.wewrite.MoveProtoData.protoData.Builder.class);
      }

      // Construct using com.example.wewrite.MoveProtoData.protoData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        moveType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cursorChange_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        valid_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.wewrite.MoveProtoData.internal_static_wewrite_protoData_descriptor;
      }

      public com.example.wewrite.MoveProtoData.protoData getDefaultInstanceForType() {
        return com.example.wewrite.MoveProtoData.protoData.getDefaultInstance();
      }

      public com.example.wewrite.MoveProtoData.protoData build() {
        com.example.wewrite.MoveProtoData.protoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.wewrite.MoveProtoData.protoData buildPartial() {
        com.example.wewrite.MoveProtoData.protoData result = new com.example.wewrite.MoveProtoData.protoData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.moveType_ = moveType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cursorChange_ = cursorChange_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.valid_ = valid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.wewrite.MoveProtoData.protoData) {
          return mergeFrom((com.example.wewrite.MoveProtoData.protoData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.wewrite.MoveProtoData.protoData other) {
        if (other == com.example.wewrite.MoveProtoData.protoData.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasMoveType()) {
          setMoveType(other.getMoveType());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000004;
          text_ = other.text_;
          onChanged();
        }
        if (other.hasCursorChange()) {
          setCursorChange(other.getCursorChange());
        }
        if (other.hasValid()) {
          setValid(other.getValid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.wewrite.MoveProtoData.protoData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.wewrite.MoveProtoData.protoData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 user_id = 1;
      private long userId_ ;
      /**
       * <code>optional int64 user_id = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 move_type = 2;
      private int moveType_ ;
      /**
       * <code>optional int32 move_type = 2;</code>
       */
      public boolean hasMoveType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 move_type = 2;</code>
       */
      public int getMoveType() {
        return moveType_;
      }
      /**
       * <code>optional int32 move_type = 2;</code>
       */
      public Builder setMoveType(int value) {
        bitField0_ |= 0x00000002;
        moveType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 move_type = 2;</code>
       */
      public Builder clearMoveType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        moveType_ = 0;
        onChanged();
        return this;
      }

      // optional string text = 3;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 3;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }

      // optional int64 cursor_change = 4;
      private long cursorChange_ ;
      /**
       * <code>optional int64 cursor_change = 4;</code>
       */
      public boolean hasCursorChange() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 cursor_change = 4;</code>
       */
      public long getCursorChange() {
        return cursorChange_;
      }
      /**
       * <code>optional int64 cursor_change = 4;</code>
       */
      public Builder setCursorChange(long value) {
        bitField0_ |= 0x00000008;
        cursorChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 cursor_change = 4;</code>
       */
      public Builder clearCursorChange() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cursorChange_ = 0L;
        onChanged();
        return this;
      }

      // optional bool valid = 5;
      private boolean valid_ ;
      /**
       * <code>optional bool valid = 5;</code>
       */
      public boolean hasValid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool valid = 5;</code>
       */
      public boolean getValid() {
        return valid_;
      }
      /**
       * <code>optional bool valid = 5;</code>
       */
      public Builder setValid(boolean value) {
        bitField0_ |= 0x00000010;
        valid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool valid = 5;</code>
       */
      public Builder clearValid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        valid_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wewrite.protoData)
    }

    static {
      defaultInstance = new protoData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:wewrite.protoData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wewrite_protoData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wewrite_protoData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013moves.proto\022\007wewrite\"c\n\tprotoData\022\017\n\007u" +
      "ser_id\030\001 \001(\003\022\021\n\tmove_type\030\002 \001(\005\022\014\n\004text\030" +
      "\003 \001(\t\022\025\n\rcursor_change\030\004 \001(\003\022\r\n\005valid\030\005 " +
      "\001(\010B$\n\023com.example.wewriteB\rMoveProtoDat" +
      "a"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_wewrite_protoData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_wewrite_protoData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wewrite_protoData_descriptor,
              new java.lang.String[] { "UserId", "MoveType", "Text", "CursorChange", "Valid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
